### ISSUE TITLE
permission denied issue

### ISSUE THREAD

**Issue by bshetti** [kubernetes-up-and-running/kuard#11]
I am following the kubernetes up and running book. 
I created the following:

FROM alpine
MAINTAINER Kelsey Hightower <kelsey.hightower@kuar.io>
COPY bin/kuard /kuard
ENTRYPOINT ["/kuard"]

Ran:
docker build -t kuard-amd64:1 .

then ran this:
docker run -d --name kuard \
  --publish 8080:8080 \
  gcr.io/kuar-demo/kuard-amd64:1

Error 
ubuntu@ip-172-31-17-121:~/kuard$ sudo docker run -d --name kuard --publish 8080:8080 kuard-amd64:1
63d568a095758b5638200f30b964e9a4919f044be9871281658f6a47b18e1202
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/kuard\": permission denied".

**Comment by kapalal** [comment]
Same issue here i've tried to change the permission on /kuard with a RUN chmod +x but i still get the permission denied error

**Comment by jbeda** [comment]
What version of docker are you using? What is the OS/architecture?

**Comment by jackiedo91** [comment]
I got the same issue on ubuntu 16

**Comment by stmcginnis** [comment]
Sounds like you haven't added your user to the docker group to have non-root permissions. Make sure you've run:

sudo usermod -aG docker $USER

Then log out and back in again. You can test this is working right before attempting the examples from the book by running:

docker run hello-world

And making sure that is working right first.

**Comment by jackiedo91** [comment]
@stmcginnis thank for your comment. I still get the error after applying your advice.
I have no issues when working with other images of my personal projects.

**Comment by jbeda** [comment]
Hi all -- I updated the README with some steps that work for me -- https://github.com/kubernetes-up-and-running/kuard#manual-docker-build.  

Can y'all try that out and let me know if it works?  If it does I'll fix up the book for the next edition to make this more clear.

**Comment by jackiedo91** [comment]
@jbeda Thank for your quickly support, after update the dockerfile with the new config, I got a new issue
=== Dockerfile ===
FROM alpine
COPY bin/1/amd64/kuard /kuard
ENTRYPOINT ["/kuard"]

=== Issue after run "docker build -t kuard-amd64:1 ." ===
`Step 1/3 : FROM alpine
latest: Pulling from library/alpine
ff3a5c916c92: Pull complete 
Digest: sha256:7df6db5aa61ae9480f52f0b3a06a140ab98d427f86d8d5de0bedab9b8df6b1c0
Status: Downloaded newer image for alpine:latest
 ---> 3fd9065eaf02
Step 2/3 : COPY bin/1/amd64/kuard /kuard
COPY failed: stat /var/lib/docker/tmp/docker-builder419379731/bin/1/amd64/kuard: no such file or directory`

**Comment by jbeda** [comment]
@jackiedo91 Did you run `make` from the base directory?  That is the one that should be creating the binary that we are looking to put in there.

**Comment by jeffreyt** [comment]
Just stumbled upon this thread but I'm also following along with the book and running the make file was the missing step for me.  Thank you!

**Comment by jbeda** [comment]
Great!  I'll close this now.  Other folks -- please file a new issue or reopen if you think things are still broken.

**Comment by vogd** [comment]
I have copied kuard file I built to the /bin/kuard. Not to change the path from the one I have in original book.
Still error returned by Docker once Step 3 executed from the Dockerfile as jaffreyt reported.
Sending build context to Docker daemon  10.54GB
Step 1/4 : FROM alpine
 ---> 3f53bb00af94
Step 2/4 : MAINTAINER Kelsey Hightower <kelsey.hightower@kuar.io>
 ---> Using cache
 ---> 091c62fae89e
Step 3/4 : COPY /bin/kuard /kuard
COPY failed: stat /var/lib/docker/tmp/docker-builder108399387/bin/kuard: no such file or directory


File indeed exist:
ll /bin/kuard
-rwxr-xr-x 1 root root 15885965 Dec 27 15:57 /bin/kuard*
root@pl# /bin/kuard
2018/12/27 16:07:22 Starting kuard version: v0.7.2-4-g423174b-1
2018/12/27 16:07:22 **********************************************************************
2018/12/27 16:07:22 * WARNING: This server may expose sensitive
2018/12/27 16:07:22 * and secret information. Be careful.
2018/12/27 16:07:22 **********************************************************************
2018/12/27 16:07:22 Config: 
{
  "address": ":8080",
  "debug": false,
  "debug-sitedata-dir": "./sitedata",
  "keygen": {
    "enable": false,
    "exit-code": 0,
    "exit-on-complete": false,
    "memq-queue": "",
    "memq-server": "",
    "num-to-gen": 0,
    "time-to-run": 0
  },
  "liveness": {
    "fail-next": 0
  },
  "readiness": {
    "fail-next": 0
  },
  "tls-address": ":8443",
  "tls-dir": "/tls"
}
2018/12/27 16:07:22 Could not find certificates to serve TLS
2018/12/27 16:07:22 Serving on HTTP on :8080

Binary works fine. Connections checked to be accepted, but why the file is not copied by docker ?
