### ISSUE TITLE
Include curl in kuard Docker image

### ISSUE THREAD

**Issue by sslavic** [kubernetes-up-and-running/kuard#12]
Please have `curl` installed in kuard Docker image so that the image can be used for testing Istio with mutual TLS enabled and liveness/readiness probes defined for kuard deployment.

Because of a bug in Istio, when mutual TLS is enabled, httpGet as liveness/readiness probe does not work and using exec/command+curl is a workaround (see https://github.com/istio/istio/issues/1194#issuecomment-345024261).

**Comment by jbeda** [comment]
This is a little difficult to do without breaking cross-arch dockerfiles.  Right now we don't run any code in a container when building the deploy images.  To get curl installed we'd have to (a) assume the base image/os we are using and (b) run the appropriate package manager to get curl.

Feel free to build/deploy your own test versions by hacking `Dockerfile.kuard` to test things out.  You can look at `BASEIMAGE` in `rules.mk` to change the base image that is being used.

**Comment by sslavic** [comment]
Silly me, thought https://github.com/kubernetes-up-and-running/kuard/blob/master/Dockerfile.build#L30 was being used as Dockerfile for the kuard image, while it's just the build image.
