### ISSUE TITLE
i am unable to pull the image 

### ISSUE THREAD

**Issue by puppetbabu** [kubernetes-up-and-running/kuard#16]
Hi,
I am following this book and  unable to create the image from dockerfile (chapter2 ) and also while pulling the image i am getting the "unknown authority". please help me to download this image

[root@minion1 ~]# docker pull gcr.io/kuar-demo/kuard-amd64:1
Trying to pull repository gcr.io/kuar-demo/kuard-amd64 ...
1: Pulling from gcr.io/kuar-demo/kuard-amd64

2fdfe1cd78c2: Pulling fs layer
fd39a7f0b8e8: Pulling fs layer
error pulling image configuration: Get https://storage.googleapis.com/artifacts.kuar-demo.appspot.com/containers/images/sha256:a92da648d493e06a2b4e63cb478c77b355800044054e262c561e65f343e959c8: x509: certificate signed by unknown authority

Regards,
-Hari

**Comment by jbeda** [comment]
Hi Hari,

I just tried this with an up to date docker install on my mac.  My guess is that the node you are running on has an old/limited root certificate bundle and so TLS is failing.  Or there is some "man in the middle" type attack going on that is preventing docker from validating the TLS connection to google storage.

I'm going to close this as I'm pretty sure this isn't an issue specific to kuard.
