### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ehernandez-xk** [kubernetes-up-and-running/kuard#22]
Hello, first thanks for this useful project

I think is important to update or mention in the documentation that a newer version may be available

The run command is:
```
kubectl run --restart=Never --image=gcr.io/kuar-demo/kuard-amd64:1 kuard
kubectl port-forward kuard 8080:8080
```
But it seems that new versions are available eg. `gcr.io/kuar-demo/kuard-amd64:3`

I can do a PR to improve this 😄

What do you think?

**Comment by jbeda** [comment]
Hi @ehernandez-xk -- this stuff is a little confusing.  The versions 1,2,3 are fake versions that all are the same binary and are used to demonstrate version upgrades in the book.  The only difference between them is the version string.  I'll look at the readme and see if there are some clarifications I can make.
