### ISSUE TITLE
Can not create Pod

### ISSUE THREAD

**Issue by powerofviva** [kubernetes-up-and-running/kuard#39]
Hi,

I am not able  to create pod, I tried both yaml configuration and docker run (page 49 second edition). I am getting:

 docker run -d --name kuard --publish 8080:8080 gcr.io/kuard-demo/kuard-amd64:blue
Unable to find image 'gcr.io/kuard-demo/kuard-amd64:blue' locally
docker: Error response from daemon: Head https://gcr.io/v2/kuard-demo/kuard-amd64/manifests/blue: unknown: Project 'project:kuard-demo' not found or deleted.

It is appreciated  to let me know how to fix that issue.

**Comment by powerofviva** [comment]
Anyone is checking here?!

**Comment by chrikoch** [comment]
I think I'm having the same problem. Perhaps the Image is not public?

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  2s    default-scheduler  Successfully assigned default/kuard to dev-03768
  Normal   Pulling    1s    kubelet            Pulling image "gcr.io/kuar-demo/kuard-am64:blue"
  Warning  Failed     1s    kubelet            Failed to pull image "gcr.io/kuar-demo/kuard-am64:blue": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/kuar-demo/kuard-am64:blue not found: manifest unknown: Failed to fetch "blue" from request "/v2/kuar-demo/kuard-am64/manifests/blue".
  Warning  Failed     1s    kubelet            Error: ErrImagePull
  Normal   BackOff    0s    kubelet            Back-off pulling image "gcr.io/kuar-demo/kuard-am64:blue"
  Warning  Failed     0s    kubelet            Error: ImagePullBackOff
```

**Comment by ericsmalling** [comment]
You appear to have misspelled the registry account name, it's `kuar-demo` not `kuard-demo`

Try `docker run -d --name kuard --publish 8080:8080 gcr.io/kuar-demo/kuard-amd64:blue` instead.

**Comment by lachie83** [comment]
Resolved via this comment https://github.com/kubernetes-up-and-running/kuard/issues/39#issuecomment-916487491
