### ISSUE TITLE
Gcloud enable container command missing

### ISSUE THREAD

**Issue by allanstevanp** [kubernetes-up-and-running/kuard#49]
Hi there,

Just to let y'all know that in Chapter 3 (page 51) it's missing the _gcloud services enable container_ command before the _gcloud container clusters create kuar-cluster_

Not a big deal, but can save some minutes for the readers.

Thanks,
Allan.

**Comment by lachie83** [comment]
Hi @allanstevanp. Thank you very much for providing this report. I've raised an errata and will add a note callout box mentioning that you may need to first enable Kubernetes Engine API with the command you provided.
